
version: '3'

services:

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
  # This container's job is just run the command to initialize the replica set.
  # It will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

  # user toto
  # email 5hc05@vmani.com
  # pass password
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
    depends_on:
      - mongo
    ports:
      - 3000:3000

  # waheko@duck2.club
  # hubot
  # password
  # hubot:
  #   image: rocketchat/hubot-rocketchat:latest
  #   environment:
  #     # - MONGODB_URL=mongodb://mongo:27017/hubot
  #     - ROCKETCHAT_URL=http://localhost:3000
  #     - ROCKETCHAT_ROOM=''
  #     - BOT_NAME=hubot
  #     - ROCKETCHAT_USER=hubot
  #     - ROCKETCHAT_PASSWORD=password
  #     - ROCKETCHAT_AUTH=password
  #     - HUBOT_NAME=hubot
  #     - HUBOT_ADAPTER=rocketchat
  #     - HUBOT_HTTPD=true
  #     - LISTEN_ON_ALL_PUBLIC=true
  #     - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-pugme,hubot-greetings,hubot-json-rest,hubot-diagnostics
  #   links:
  #     - rocketchat:rocketchat
  #   # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  #   ports:
  #     - 3001:8081
  #   restart: unless-stopped
  #   volumes:
  #     - ./scripts:/home/hubot/scripts
      

  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=GENERAL
      - BOT_NAME=hubot
      - ROCKETCHAT_USER=hubot
      - ROCKETCHAT_PASSWORD=password
      - ROCKETCHAT_AUTH=password
      # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - rocketchat
    volumes:
      - ./scripts:/home/hubot/scripts
    # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080
